#!/bin/bash

EXT_NAME=$1

VERSION=`xmllint --xpath 'string(//extension/version)' $EXT_NAME.xml`
JOOMLA_VERSION=`xmllint --xpath 'substring(//extension/@version, 1, 1)' $EXT_NAME.xml`

SCRIPTFILE=`xmllint --xpath '(//extension/scriptfile)/text()' $EXT_NAME.xml`

FILES="$SCRIPTFILE"

FILE_COUNTS=`xmllint --xpath 'count(//extension/files)' $EXT_NAME.xml`
for ((j=1; j<=FILE_COUNTS; j++)); do
  FILES_FOLDER=`xmllint --xpath 'string((//extension/files)['"$j"']/@folder)' $EXT_NAME.xml`

  if  [ ! -z "$FILES_FOLDER" ]; then
    FILES_FOLDER="$FILES_FOLDER/"
  fi

  wwCount=`xmllint --xpath 'count((//extension/files)['"$j"']/*)' $EXT_NAME.xml`
  for ((i=1; i<=wwCount; i++)); do
          wwExtracted=`xmllint --xpath '((//extension/files)['"$j"']/*)['"$i"']/text()' $EXT_NAME.xml`
          FILES="$FILES ${FILES_FOLDER}${wwExtracted}"
  done
done


FILE_COUNTS=`xmllint --xpath 'count(//extension/administration/files)' $EXT_NAME.xml`
for ((j=1; j<=FILE_COUNTS; j++)); do
  FILES_FOLDER=`xmllint --xpath 'string((//extension/administration/files)['"$j"']/@folder)' $EXT_NAME.xml`

  if  [ ! -z "$FILES_FOLDER" ]; then
    FILES_FOLDER="$FILES_FOLDER/"
  fi

  wwCount=`xmllint --xpath 'count((//extension/administration/files)['"$j"']/*)' $EXT_NAME.xml`
  for ((i=1; i<=wwCount; i++)); do
          wwExtracted=`xmllint --xpath '((//extension/administration/files)['"$j"']/*)['"$i"']/text()' $EXT_NAME.xml`
          FILES="$FILES ${FILES_FOLDER}${wwExtracted}"
  done
done


MEDIA_FILES_FOLDER=`xmllint --xpath 'string(//extension/media/@folder)' $EXT_NAME.xml`
wwCount=`xmllint --xpath 'count(//extension/media/*)' $EXT_NAME.xml`
for ((i=1; i<=wwCount; i++)); do
        wwExtracted=`xmllint --xpath '(//extension/media/*)['"$i"']/text()' $EXT_NAME.xml`
        FILES="$FILES ${MEDIA_FILES_FOLDER}/${wwExtracted}"
done

zip -r "${EXT_NAME}_${JOOMLA_VERSION}.x_${VERSION}.zip" $FILES $EXT_NAME.xml
